### ISSUE TITLE
Limit number

### ISSUE THREAD

**Issue by maciz84** [jesseokeya/Forbes400#1]
Hi there,

This is an awesome API by the way...GREAT JOB!. One question though, is there a way I can limit the data to say top 100 as it is a lot of data to crunch over the wire with 400 items. I think this would be a nice feature to have.

**Comment by jesseokeya** [comment]
Hi, 
Yes there is just do this https://forbes400.herokuapp.com/api/forbes400?limit=100 <https://forbes400.herokuapp.com/api/forbes400?limit=100> thanks for using the api. If there are anymore improvements you’ll like to see let me know

**Comment by jesseokeya** [comment]
I should also probably add that to the documentations too.

**Comment by maciz84** [comment]
@jesseokeya thanks man, if you could add it to the documentation that might help other people. Again thanks so much I am loving this API 👍

**Comment by maciz84** [comment]
@jesseokeya  Also do you have a gitter chat room?

**Comment by jesseokeya** [comment]
Yh I just added it to the documentation now. I don’t have a gitter chat room. But you could invite me to yours. I’ll definitely join. Again thanks for letting me know about the limit issue.

**Comment by maciz84** [comment]
No worries I have created a room and invited you
