### ISSUE TITLE
Is there a route to fetch a specific character?

### ISSUE THREAD

**Issue by kanake10** [jesseokeya/Forbes400#35]

**Comment by jesseokeya** [comment]
Not at the moment that can be a feature to easily add. If you want to take it on that would be great

**Comment by kanake10** [comment]
Thats ok,
Also noted, some of the images returns an error on postman once I try to fetch the data .

**Comment by jesseokeya** [comment]
Yeah, I noticed that too. That's from Forbes themselves. I usually use a placeholder image for those if they occur

**Comment by kanake10** [comment]
ok,nice.
This was really a nice API ,wished it would work correctly.

Used the API to create a mobile app.This the link to the app.

https://github.com/kanake10/Forbes

**Comment by jesseokeya** [comment]
Ah i see. So `heroku` shut down their free tier. I'm now using `render` and the correct API is now  [forbes400.onrender.com/](https://forbes400.onrender.com/)
