### ISSUE TITLE
Heroku free plans are getting closed

### ISSUE THREAD

**Issue by abdullahumer** [jesseokeya/Forbes400#36]
Any plan to move this project to somewhere else? I have been using this for testing purposes.

I tried to deploy it on my own server but its missing the env variables. Could you please post the complete details on how we can deploy it on our own server?

**Comment by TDGNate** [comment]
^^^

**Comment by jesseokeya** [comment]
Sorry just saw this. The Forbes URL is `https://www.forbes.com/forbesapi/person/rtb/0/-estWorthPrev/true.json`. I also redeployed the app on `render` and the new URL to use the API is `https://forbes400.onrender.com`

**Comment by TDGNate** [comment]
Ty 🙏
