### ISSUE TITLE
[https://forbes400.onrender.com/] Site is not opening and API calling is not going to success.

### ISSUE THREAD

**Issue by MeetDesaii** [jesseokeya/Forbes400#48]
[https://forbes400.onrender.com/] Site is not opening and API calling is not going to success... Can you explain sir that what's happening? Any updates done by you?

**Comment by MeetDesaii** [comment]
[https://forbes400.onrender.com/] Site is not opening and API calling is not going to success... Can you explain sir that what's happening? Any updates done by you?

**Comment by jesseokeya** [comment]
It seems like `render` went down earlier today. It should be back up. Are you still having issues retrieving the API response?

**Comment by MeetDesaii** [comment]
Solved mate.. !!
